services:
  llama-cpp-gpu:
    image: ghcr.io/ggml-org/llama.cpp:server-cuda
    ports:
      - "8081:8080"
    volumes:
      - ./models:/models:ro
    environment:
      - CUDA_VISIBLE_DEVICES=0
    command: >
      -m /models/${LLAMA_MODEL_FILE}
      --host 0.0.0.0
      --port 8080
      --n-gpu-layers ${LLAMA_N_GPU_LAYERS:-99}
      --ctx-size ${LLAMA_CTX_SIZE:-32768}
      --temp ${LLAMA_TEMP:-1.0}
      --top-k ${LLAMA_TOP_K:-64}
      --top-p ${LLAMA_TOP_P:-0.95}
      --min-p ${LLAMA_MIN_P:-0.0}
      --repeat-penalty ${LLAMA_REPEAT_PENALTY:-1.0}
      --threads ${LLAMA_THREADS:-8}
      --parallel ${LLAMA_N_PARALLEL:-4}
      --cont-batching
      --log-verbose
      --mlock
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]