services:
  llm-cpu:
    image: ghcr.io/ggml-org/llama.cpp:server
    ports:
      - "${LLM_PORT:-8080}:8080"
    volumes:
      - ./models:/models:ro
    environment:
      - LLAMA_ARG_MODEL=/models/${LLM_MODEL_FILE}
      - LLAMA_ARG_CTX_SIZE=${LLM_CTX_SIZE:-2048}
      - LLAMA_ARG_N_PARALLEL=${LLM_N_PARALLEL:-1}
    command: >
      -m /models/${LLM_MODEL_FILE}
      --host 0.0.0.0
      --port 8080
      --ctx-size ${LLM_CTX_SIZE:-32768}
      --temp ${LLM_TEMP:-1.0}
      --top-k ${LLM_TOP_K:-64}
      --top-p ${LLM_TOP_P:-0.95}
      --min-p ${LLM_MIN_P:-0.0}
      --repeat-penalty ${LLM_REPEAT_PENALTY:-1.0}
      --threads ${LLM_THREADS:-8}
      --parallel ${LLM_N_PARALLEL:-4}
      --cont-batching
      --log-verbose
      --mlock
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  embd-cpu:
    image: ghcr.io/ggml-org/llama.cpp:server
    ports:
      - "${EMBD_PORT:-8081}:8080"
    volumes:
      - ./models:/models:ro
    environment:
      - LLAMA_ARG_MODEL=/models/${EMBD_MODEL_FILE}
      - LLAMA_ARG_CTX_SIZE=${EMBD_CTX_SIZE:-2048}
      - LLAMA_ARG_N_PARALLEL=${EMBD_N_PARALLEL:-1}
    command: >
      -m /models/${EMBD_MODEL_FILE}
      --embeddings
      --host 0.0.0.0
      --port 8080
      --ctx-size ${EMBD_CTX_SIZE:-32768}
      --pooling ${EMBD_POOLING:-mean}
      --threads ${EMBD_THREADS:-8}
      --parallel ${EMBD_N_PARALLEL:-4}
      --log-verbose
      --mlock
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
